Repository cloudfoundry/service-fabrik-boshrelease, pull requests merged in 2018-05, with the labels that each got.

#70 Bug/unmount issue
  jobs/docker/templates/bin/docker_ctl.erb
  jobs/docker/templates/bin/job_properties.sh.erb
Labels: unscheduled

#67 Feature/iptables manager
  jobs/iptables-manager/monit
  jobs/iptables-manager/spec
  jobs/iptables-manager/templates/bin/iptables-manager_ctl.erb
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-broker/templates/config/settings.yml.erb
  jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Labels: DO-NOT-MERGE, unscheduled

#66 Modularize service-fabrik-broker source code
  jobs/service-fabrik-broker/templates/bin/service-fabrik-broker_ctl.erb
  jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
  jobs/service-fabrik-scheduler/templates/bin/service-fabrik-scheduler_ctl.erb
  packages/service-fabrik-broker/packaging
  packages/service-fabrik-broker/pre_packaging
  packages/service-fabrik-broker/spec
Labels: unscheduled

#71 Added missing prop service_addon_jobs
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Labels: unscheduled

#73 HA Support for Service Fabrik
  config/blobs.yml
  jobs/keepalived/monit
  jobs/keepalived/spec
  jobs/keepalived/templates/bin/action.sh.erb
  jobs/keepalived/templates/bin/get_keepalived_state.sh.erb
  jobs/keepalived/templates/bin/get_sf_broker_status.sh.erb
  jobs/keepalived/templates/bin/keepalived_ctl.erb
  jobs/keepalived/templates/bin/notify.sh.erb
  jobs/keepalived/templates/config/keepalived.conf.erb
  jobs/service-fabrik-broker/monit
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-broker/templates/bin/drain.erb
  jobs/service-fabrik-broker/templates/bin/health_check.erb
  jobs/service-fabrik-broker/templates/config/settings.yml.erb
  packages/aws-cli/packaging
  packages/aws-cli/spec
  packages/keepalived/packaging
  packages/keepalived/spec
  packages/python/packaging
  packages/python/spec
Labels: DO-NOT-MERGE, High Availability, unscheduled

#76 Fix upload-release failure in Bosh-Lite
  templates/cloud-config-boshlite.yml
  templates/deployment.yml
  templates/ops-file-boshlite.yml
Labels: unscheduled

#79 Modifying the version of AWS Cli and removing installation of python dev
  config/blobs.yml
  packages/aws-cli/packaging
Labels: unscheduled

#81 Feature/seccomp
  config/blobs.yml
  jobs/service-fabrik-deployment-hooks/spec
  jobs/service-fabrik-deployment-hooks/templates/bin/service-fabrik-deployment-hooks_ctl.erb
  jobs/service-fabrik-deployment-hooks/templates/config/settings.yml.erb
  packages/libseccomp/packaging
  packages/libseccomp/spec
  packages/service-fabrik-deployment-hooks/packaging
  packages/service-fabrik-deployment-hooks/spec
  services/actions/Blueprint_PreCreate
Labels: unscheduled

#82 Modifying the keepalived conf to resolve the ips issue
  jobs/keepalived/templates/config/keepalived.conf.erb
Labels: unscheduled

#83 Removing the dependency on spec.bootstrap to fix the master ip for sf-broker
  jobs/keepalived/templates/config/keepalived.conf.erb
Labels: unscheduled

#84 Removing the dependency on spec.bootstrap to fix the master ip for sf-broker
  jobs/keepalived/templates/config/keepalived.conf.erb
Labels: unscheduled
