Repository cloudfoundry/service-fabrik-boshrelease, pull requests merged in 2018-08, with the labels that each got.

#110 Changes to support PITR
  jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-broker/templates/config/settings.yml.erb
  jobs/service-fabrik-report/templates/config/settings.yml.erb
  jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
  templates/deployment.yml
Labels: unscheduled

#107 Ha logs
  jobs/keepalived/templates/bin/action.sh.erb
  jobs/keepalived/templates/bin/keepalived_ctl.erb
  jobs/keepalived/templates/bin/utils/openstack/generate_token
  jobs/keepalived/templates/bin/utils/openstack/port_operations
Labels: DO-NOT-MERGE, DRAFT, High Availability, unscheduled

#112 Adding configs for transaction logs delete time buffer
  jobs/service-fabrik-backup-manager/templates/config/settings.yml.erb
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-broker/templates/config/settings.yml.erb
  jobs/service-fabrik-report/templates/config/settings.yml.erb
  jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Labels: unscheduled

#106 Adding docker and bosh manager jobs
  jobs/service-fabrik-bosh-manager/monit
  jobs/service-fabrik-bosh-manager/spec
  jobs/service-fabrik-bosh-manager/templates/bin/job_properties.sh.erb
  jobs/service-fabrik-bosh-manager/templates/bin/service-fabrik-bosh-manager_ctl.erb
  jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
  jobs/service-fabrik-bosh-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-docker-manager/monit
  jobs/service-fabrik-docker-manager/spec
  jobs/service-fabrik-docker-manager/templates/bin/job_properties.sh.erb
  jobs/service-fabrik-docker-manager/templates/bin/service-fabrik-docker-manager_ctl.erb
  jobs/service-fabrik-docker-manager/templates/config/settings.yml.erb
  jobs/service-fabrik-docker-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-virtualhost-manager/monit
  jobs/service-fabrik-virtualhost-manager/spec
  jobs/service-fabrik-virtualhost-manager/templates/bin/job_properties.sh.erb
  jobs/service-fabrik-virtualhost-manager/templates/bin/service-fabrik-virtualhost-manager_ctl.erb
  jobs/service-fabrik-virtualhost-manager/templates/config/settings.yml.erb
  jobs/service-fabrik-virtualhost-manager/templates/config/syslog_forwarding.conf.erb
Labels: DEV-PIPELINE-SUCCESS, SF2.0, unscheduled

#115 Update README with apiserver setup docs
  README.md
Labels: unscheduled

#116 Update cloud config
  templates/cloud-config-boshlite.yml
Labels: unscheduled

#114 Add kubectl config script
  scripts/set-kubeconfig
Labels: unscheduled

#117 Add event log config for backup manager
  jobs/service-fabrik-backup-manager/spec
  jobs/service-fabrik-backup-manager/templates/config/eventlog-config-external.yml.erb
Labels: unscheduled

#118 Restore mgr fix rel.08b
  jobs/service-fabrik-backup-manager/spec
  jobs/service-fabrik-backup-manager/templates/config/eventlog-config-external.yml.erb
Labels: unscheduled
