Repository cloudfoundry/service-fabrik-boshrelease, pull requests merged in 2019-05, with the labels that each got.

#174 Adding config for ArchiveMeteredEvents job
  jobs/service-fabrik-scheduler/spec
  jobs/service-fabrik-scheduler/templates/config/settings.yml.erb
Labels: unscheduled

#170 Modifying health check script
  jobs/keepalived/templates/bin/notify.sh.erb
  jobs/service-fabrik-broker/templates/bin/health_check.erb
Labels: DEV-PIPELINE-SUCCESS, unscheduled

#173 Remove syslog forwarding from jobs
  jobs/docker/spec
  jobs/docker/templates/bin/docker_ctl.erb
  jobs/docker/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-backup-manager/spec
  jobs/service-fabrik-backup-manager/templates/bin/service-fabrik-backup-manager_ctl.erb
  jobs/service-fabrik-backup-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-bosh-manager/spec
  jobs/service-fabrik-bosh-manager/templates/bin/service-fabrik-bosh-manager_ctl.erb
  jobs/service-fabrik-bosh-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-broker/templates/bin/service-fabrik-broker_ctl.erb
  jobs/service-fabrik-broker/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-docker-manager/spec
  jobs/service-fabrik-docker-manager/templates/bin/service-fabrik-docker-manager_ctl.erb
  jobs/service-fabrik-docker-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-postgresqlmt-operator/spec
  jobs/service-fabrik-postgresqlmt-operator/templates/bin/pre_start.erb
  jobs/service-fabrik-postgresqlmt-operator/templates/config/bpm.yml.erb
  jobs/service-fabrik-postgresqlmt-operator/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-report/spec
  jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
  jobs/service-fabrik-report/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-scheduler/spec
  jobs/service-fabrik-scheduler/templates/bin/service-fabrik-scheduler_ctl.erb
  jobs/service-fabrik-scheduler/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-serviceflow-manager/spec
  jobs/service-fabrik-serviceflow-manager/templates/bin/pre_start.erb
  jobs/service-fabrik-serviceflow-manager/templates/config/bpm.yml.erb
  jobs/service-fabrik-serviceflow-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-virtualhost-manager/spec
  jobs/service-fabrik-virtualhost-manager/templates/bin/service-fabrik-virtualhost-manager_ctl.erb
  jobs/service-fabrik-virtualhost-manager/templates/config/syslog_forwarding.conf.erb
  jobs/swarm_manager/spec
  jobs/swarm_manager/templates/bin/swarm_manager_ctl
  jobs/swarm_manager/templates/config/syslog_forwarding.conf.erb
Labels: unscheduled

#177 Fix keepalived ARP cache
  jobs/keepalived/templates/bin/action.sh.erb
  jobs/keepalived/templates/config/keepalived.conf.erb
Labels: enhancement, unscheduled
