Repository cloudfoundry/service-fabrik-boshrelease, pull requests merged in 2019-01, with the labels that each got.

#142 Upgrading APIServer
  config/blobs.yml
  packages/apiserver/packaging
  packages/apiserver/spec
Labels: DEV-PIPELINE-SUCCESS, unscheduled

#141 Adding webhook job back in the apiserver local
  templates/apiserver.yml
Labels: unscheduled

#140 Enable instance sharing on Cloud Foundry
  jobs/service-fabrik-bosh-manager/templates/config/settings.yml.erb
  jobs/service-fabrik-broker/spec
  jobs/service-fabrik-broker/templates/config/settings.yml.erb
Labels: unscheduled

#144 deployment hooks had missed copying package.json
  packages/service-fabrik-deployment-hooks/packaging
Labels: unscheduled

#146 Move ModLoads in Rsyslog to one single Configuration-File
  jobs/docker/templates/bin/docker_ctl.erb
  jobs/docker/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-backup-manager/templates/bin/service-fabrik-backup-manager_ctl.erb
  jobs/service-fabrik-backup-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-bosh-manager/templates/bin/service-fabrik-bosh-manager_ctl.erb
  jobs/service-fabrik-bosh-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-broker/templates/bin/service-fabrik-broker_ctl.erb
  jobs/service-fabrik-broker/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-docker-manager/templates/bin/service-fabrik-docker-manager_ctl.erb
  jobs/service-fabrik-docker-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-postgresqlmt-operator/templates/bin/pre_start.erb
  jobs/service-fabrik-postgresqlmt-operator/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-report/templates/bin/service-fabrik-report_ctl.erb
  jobs/service-fabrik-report/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-scheduler/templates/bin/service-fabrik-scheduler_ctl.erb
  jobs/service-fabrik-scheduler/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-serviceflow-manager/templates/bin/pre_start.erb
  jobs/service-fabrik-serviceflow-manager/templates/config/syslog_forwarding.conf.erb
  jobs/service-fabrik-virtualhost-manager/templates/bin/service-fabrik-virtualhost-manager_ctl.erb
  jobs/service-fabrik-virtualhost-manager/templates/config/syslog_forwarding.conf.erb
  jobs/swarm_manager/templates/bin/swarm_manager_ctl
  jobs/swarm_manager/templates/config/syslog_forwarding.conf.erb
Labels: unscheduled

#149 eventlog-config for cancel schedule_update API
  jobs/service-fabrik-backup-manager/templates/config/eventlog-config-external.yml.erb
  jobs/service-fabrik-broker/templates/config/eventlog-config-external.yml.erb
  jobs/service-fabrik-scheduler/templates/config/eventlog-config-external.yml.erb
Labels: DEV-PIPELINE-SUCCESS

#150 Update set-kubeconfig script
  scripts/set-kubeconfig
Labels: unscheduled

#148 changes for docker xenial migration
  config/blobs.yml
  jobs/docker/templates/bin/lvmvd_ctl.erb
  jobs/keepalived/spec
  packages/aws-cli/packaging
  packages/lvm2/packaging
  packages/lvm2/spec
  packages/python/packaging
  packages/service-fabrik-broker/packaging
  packages/service-fabrik-deployment-hooks/packaging
Labels: unscheduled

#154 Travis fix for interoperator
  .travis.yml
  config/blobs.yml
Labels: unscheduled

#155 Adding travis build badge
  README.md
Labels: unscheduled
